"""add_phone_number_to_user

Revision ID: 23afa1f373e7
Revises: e340aa3a6d1c
Create Date: 2023-03-03 21:40:22.994835

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '23afa1f373e7'
down_revision = 'e340aa3a6d1c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('phone_number', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'phone_number')
    # ### end Alembic commands ###
